###################################################
# GLobal Processing Flags
###################################################

global_processing_flags:
    # how to flag / handle extracted question data from Zooniverse -- default
    # is to convert to: 'question__<question_on_zooniverse>'
    QUESTION_DELIMITER: __
    QUESTION_PREFIX: question
    # the name to use for the main/top-level question in a survey task
    QUESTION_MAIN: species
    # the answer to the main/top-level question that indicates blank/empt images
    # these are handled differently in certain cases
    QUESTION_MAIN_EMPTY: blank

###################################################
# Pre-Processing Flags
###################################################

pre_processing_flags:
    # Input / Output Timeformats
    time_formats:
      # timeformat as stored in EXIF data (should not change)
      exif_input_datetime_format: '%Y:%m:%d %H:%M:%S'
      # timeformat used in output files (can be changed)
      output_date_format: '%Y-%m-%d'
      output_datetime_format: '%Y-%m-%d %H:%M:%S'
      output_time_format: '%H:%M:%S'
      # the default timezone is only relevant for file creation dates
      # it has no effect on datetime if EXIF data is available,
      # if EXIF data is not available, the file-creation date is used instead
      # this must be a 'Pytz' module compatible name
      default_timezone: Africa/Johannesburg
    #############################
    # EXIF Data Extraction
    #############################
    # Order of EXIF timestamp data to consider for the 'datetime'
    # attribute of the image (first non-empty found in the EXIF tags)
    exif_data_timestamps:
     - DateTime
     - DateTimeOriginal
     - EXIF:DateTime
     - EXIF:DateTimeOriginal
    # EXIF data is grouped -- this specifies which groups to extract
    exif_tag_groups_to_extract:
     - EXIF
     - MakerNotes
     - Composite
    # exclude specific exif tags: default is to exclude binary data like
    # thumbnail versions of the image
    exif_tags_to_exclude:
     - EXIF:ThumbnailImage
     - MakerNotes:PreviewImage
    #############################
    # Checks
    #############################
    # list of image checks -- changing this is not recommend: unclear impact
    image_checks:
     - all_black
     - all_white
     - corrupt_file
     - corrupt_exif
     - empty_exif
     - time_lapse
     - time_too_new
     - time_too_old
     - captures_with_too_many_images
    image_check_parameters:
     # a 'black' pixel is defined as a pixel whose RGB values are all
     # below 30 (default), an image is considered 'all_black' if at least
     # 0.8 (80%) are below that threshold
     all_black:
       percent: 0.8
       thresh: 30
     # a 'white' pixel is defined as a pixel whose RGB values are all
     # above 200 (default), an image is considered 'all_white' if at least
     # 0.8 (80%) are above that threshold
     all_white:
       percent: 0.8
       thresh: 200
     # captures with more than 'max_images' images fail that check
     captures_with_too_many_images:
       max_images: 3
     # subsequent images <= N seconds apart will be grouped into the
     # same capture (X1, X2, X3, X4 grouped if each difference is <= N)
     capture_delta_max_seconds: 5
     # max allowed consequetive days without captures -- otherwise flagged
     time_lapse_days:
       max_days: 30
     # general time window (years) -- typically specified via parameters
     time_too_new:
       max_year: 9999
     time_too_old:
       min_year: 1970
    # Group the different checks to propose automatic check actions
    image_checks_propose_invalidate:
     - all_black
     - all_white
     - corrupt_exif
     - empty_exif
    image_checks_propose_delete:
     - corrupt_file
    image_checks_propose_time:
     - time_lapse
     - time_too_new
     - time_too_old
     - captures_with_too_many_images
    #############################
    # Actions
    #############################
    # only these actions are valid
    allowed_actions_to_take:
      - delete
      - invalidate
      - timechange
      - mark_no_upload
      - mark_datetime_uncertain
      - ok
    # flags to create -- can be set by actions
    image_flags_to_create:
      - image_was_deleted
      - image_is_invalid
      - image_no_upload
      - image_datetime_uncertain
    # associate specific actions with flags that are set to '1' if the
    # action is taken
    map_actions_to_flags:
      delete:
        - image_was_deleted
        - image_no_upload
      invalidate:
        - image_is_invalid
        - image_no_upload
      mark_no_upload:
        - image_no_upload
      mark_datetime_uncertain:
        - image_datetime_uncertain
    # remove images from final cleaned file with the following flags
    flags_to_remove_from_cleaned:
      - image_was_deleted
    #############################
    # Legacy Codes
    #############################
    legacy_invalid_codes:
      - '1'
      - '2'
    #############################
    # Format of final cleaned file
    #############################
    final_cleaned:
      # order of first columns, any that are found will be exported in this
      # order
      first_columns:
        - capture_id
        - season
        - site
        - roll
        - capture
        - image_rank_in_capture
        - image_name
        - image_path_rel
        - datetime
        - datetime_exif
        - datetime_file_creation
        - image_is_invalid
        - image_datetime_uncertain
        - image_no_upload
        - image_was_deleted
        - action_taken
        - action_taken_reason
      # specify columns to exclude from the cleaned file, columns not in
      # 'first_columns' and not in 'exclude_columns' will be appended
      # warning: do not exclude important cols like:
      #  capture_id, season, site, roll, capture, image_rank_in_capture
      exclude_columns:
        - seconds_to_next_image_taken
        - seconds_to_last_image_taken
        - days_to_last_image_taken
        - days_to_next_image_taken
        - image_rank_in_roll
        - image_path
        - image_name_original
        - image_path_original_rel
        - image_path_original
        - date
        - time
      # flag to generally exclude EXIF data -- default is to exclude EXIF tags
      exclude_exif_data: True
      # flag to generally exclude image check flags -- default is to exclude
      exclude_image_check_flags: True


###################################################
# Flags to define the bheavior of the
# Classification Extractor
###################################################

extractor_flags:
    # This can be used to map long questions (typically full sentences without
    # blanks and special characters) to more readable ones
    # 'choice' is the default question name for the 'survey-task'
    QUESTION_NAME_MAPPER:
      arethereanyyoungpresent: young_present
      choice: species
      doyouseeanyantlers: antlers_visible
      doyouseeanyhorns: horns_visible
      howmany: count
      howmanyanimalscanyouseethathavehorns: horns_count
      question: species
    # questions not to extract
    QUESTIONS_TO_IGNORE:
     - dontcare
    # general answer mapper -- map any answer from any question to the
    # specified value
    ANSWER_MAPPER:
      0: '0'
      n: '0'
      'no': '0'
      1: '1'
      y: '1'
      'yes': '1'
    # map specific answers to specific questions -- important if different
    # anwers have the same meaning (e.g. blank)
    ANSWER_TYPE_MAPPER:
      species:
        no animals present: blank
        noanimalspresent: blank
        nothing: blank
        nothinghere: blank
        nothingthere: blank
      count:
        '1150': '11-50'
        '51': '51+'
      horns_count:
        '1150': '11-50'
        '51': '51+'
    CLASSIFICATION_INFO_TO_ADD:
     - user_name
     - user_id
     - created_at
     - subject_ids
     - workflow_id
     - workflow_version
     - classification_id
    CLASSIFICATION_INFO_MAPPER:
      subject_ids: subject_id
    QUESTIONS_OUTPUT_ORDER:
     - species
     - count
     - standing
     - resting
     - moving
     - eating
     - interacting
     - young_present
     - horns_count
     - antlers_visible

###################################################
# Subject Extractor
###################################################

subject_extractor_flags:
    # Location data refers to URL data
    SUBJECT_ADD_LOCATION_DATA: true
    SUBJECT_DATA_TO_ADD:
     - retirement_reason
     - retired_at
     - created_at
    SUBJECT_METADATA_TO_ADD:
     - '#season'
     - '#roll'
     - '#site'
     - '#capture'
     - '#capture_id'
    SUBJECT_DATA_NAME_MAPPER:
     '#capture_id': capture_id
     '#capture': capture
     '#roll': roll
     '#season': season
     '#site': site
     retirement_reason: zooniverse_retirement_reason
     retired_at: zooniverse_retired_at
     created_at: zooniverse_created_at


###################################################
# Flags to define the bheavior of the
# Plurality Aggregator
###################################################

plurality_aggregation_flags:
    # To aggregate count data (calculate quantiles) one can define
    # mappings from strings that don't represent a count value to an integer
    # that is used instead in the calculation
    COUNTS_TO_ORDINAL_MAPPER:
      '': 0
      '11-50': 11
      '51+': 12
    # define which questions are actually count questions
    QUESTION_COUNTS:
     - count
     - horns_count
    # how to aggregate the counts
    COUNT_AGGREGATION_MODES:
      - median
      - min
      - max

###################################################
# Flags for Zooniverse Uploads
###################################################

upload_flags:
    # remove any images from uploading if the following flags are
    # set to the specified value(s)
    images_to_remove_from_upload:
      image_no_upload:
        - '1'

###################################################
# Flags for the Report Generation
###################################################

report_flags:
  # remove any images (and thus captures if all images of a
  # capture are affected) for which any of the flags has any of the specified
  # values
  images_to_remove_from_report:
    image_was_deleted:
      - '1'
    image_is_invalid:
      - '1'
    image_datetime_uncertain:
      - '1'
    invalid:
      - '1'
      - '2'
  identify_humans_for_exclusion:
    - human
  # group report columns to select them when creating reports -- this affects
  # which columns are selected for different options used in the scripts
  capture_cols:
    - capture_id
    - subject_id
    - season
    - site
    - roll
    - capture_date_local
    - capture_time_local
  zooniverse_cols:
    - zooniverse_created_at
    - zooniverse_retirement_reason
    - zooniverse_retired_at
  zooniverse_url_cols:
    - zooniverse_url_
  plurality_algo_cols:
    - n_users_classified_this_subject
    - n_users_identified_this_species
    - p_users_identified_this_species
    - n_species_ids_per_user_median
    - n_species_ids_per_user_max
    - n_users_saw_a_species
    - n_users_saw_no_species
    - p_users_saw_a_species
    - pielous_evenness_index
    - species_is_plurality_consensus
  plurality_algo_cols_simple:
    - p_users_identified_this_species
    - pielous_evenness_index
  plurality_algo_cols_extended:
    - n_users_classified_this_subject
    - n_users_identified_this_species
    - n_species_ids_per_user_median
    - n_species_ids_per_user_max
    - n_users_saw_a_species
    - n_users_saw_no_species
    - p_users_saw_a_species
    - species_is_plurality_consensus


###################################################
# Flags to define the bheavior of the
# Legacy Classification Extractor
# (unlikely this needs to be ever changed)
###################################################

legacy_extractor_flags:
    ANSWER_TYPE_MAPPER:
      eating:
       'false': 0
       'true': 1
      interacting:
       'false': 0
       'true': 1
      eating:
       'false': 0
       'true': 1
      moving:
       'false': 0
       'true': 1
      resting:
       'false': 0
       'true': 1
      species:
        no animals present: blank
        nothing: blank
        '': blank
      standing:
       'false': 0
       'true': 1
      young_present:
       'false': 0
       'true': 1
    CLASSIFICATION_INFO_TO_ADD:
     - user_name
     - created_at
     - subject_id
     - capture_event_id
     - zooniverse_retirement_reason
     - season
     - site
     - roll
     - filenames
     - timestamps
     - classification_id
    CSV_HEADER_MAPPER:
     babies: young_present
     id: classification_id
     retire_reason: zooniverse_retirement_reason
     species_count: count
     subject_zooniverse_id: subject_id
     created_at: created_at
    CSV_QUESTIONS:
     - species
     - count
     - standing
     - resting
     - moving
     - eating
     - interacting
     - young_present

###################################################
# Legacy Subject Extractor
###################################################

# Subject info to add from the legacy classifications export
add_subject_info_flags_legacy:
 - season
 - roll
 - site
 - capture
 - zooniverse_retirement_reason
 - zooniverse_retired_at
 - zooniverse_created_at
 - filenames
 - timestamps
 - capture_id
